[package]
name = "decscloud-codec"
version = "0.1.0"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"


[dependencies]
prost = "0.5.0"
bytes = "0.4.12"
prost-types = "0.5.0"
serde = "1.0.101"
serde_json = "1.0.40"
serde_derive = "1.0.101"

[build-dependencies]
prost-build = "0.5.0"